ImageMood/Entities/Mood.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;
using MightyHelpers.Repository;

namespace ImageMood.Entities
{
    public class Mood : Entity, IAggregateRoot
    {
        public Mood()
        {
            MoodToImages = new Collection<MoodToImage>();
        }


        [Required(ErrorMessage = "Come on, what is your mood?")]
        [StringLength(64)]
        [RegularExpression(@"([A-яa-я ])+", ErrorMessage = "Try to express your mood with words")]
        [Remote("CheckMoodName", "Moods", ErrorMessage = "This mood already exists", AdditionalFields = "ImageId")]
        public string Name { get; set; }

        [NotMapped]
        public int ImageId { get; set; }

        public int Weight { get; private set; }

        public int ImagesCount { get; private set; }

        public ICollection<MoodToImage> MoodToImages { get; set; }

        public DateTime Created { get; private set; }


        public void AddWeight(int value)
        {
            Weight += value;
        }

        public void Create()
        {
            Created = DateTime.Now;
            ImagesCount = 1;
            Weight = 1;
        }

        protected override IEnumerable<ValidationResult> EntityRules()
        {
            return new List<ValidationResult>();
        }
    }
}

ImageMood/ViewModels/MoodViewModel.cs
namespace ImageMood.ViewModels
{
    public class MoodViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

ImageMood/Controllers/ImagesController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using ImageMood.Entities;
using ImageMood.Filters;
using ImageMood.Services;

namespace ImageMood.Controllers
{
    [JsonForAjaxCalls]
    public class ImagesController : AsyncController
    {
        private const int MaxDimension = 1024;
        private readonly IImageService _imageService;

        public ImagesController(IImageService imageService)
        {
            _imageService = imageService;
        }

        [Authorize]
        public virtual ActionResult List()
        {
            var model = _imageService.GetImages();
            
            return  View(model);
        }

        [Authorize]
        [HttpPost]
        public virtual ActionResult Delete(int id)
        {
            _imageService.DeleteImage(id);
            return Json(new {success = true}, JsonRequestBehavior.AllowGet);
        }

        public virtual ActionResult GetImage(int id, int imageId, int width = 0)
        {
            var model = _imageService.GetImage(id, imageId);
            model.Image.MaxWidth = width;
            return View(model); 
        }  
      
        public virtual ActionResult GetRandomImage()
        {
            var model = _imageService.GetRandomImages(5);
            return View(model);
        }

        [HttpPost]
        public virtual ActionResult Add(Image image)
        {
            //TODO - check Imgur uploading 
            if (!ModelState.IsValid)
            {
                return Json(new {error = "Model state invalid"});
            }

            var model = _imageService.AddImage(image, Request.ServerVariables["REMOTE_ADDR"]);



            return
                Json(
                    new
                        {
                            model.Name,
                            model.Id,
                            model.ImageMoods.First().MoodId,
                            MoodName = model.ImageMoods.First().Mood.Name,
                        });
        }


        [HttpPost]
        public virtual ActionResult Upload(HttpPostedFileBase image, string imageUrl)
        {

            try
            {

                var i = new ImageResizer.ImageJob(image ?? (object) imageUrl, "~/Content/Temp/<guid>.<ext>",
                                                  new ImageResizer.ResizeSettings(
                                                      string.Format("width={0};height={0};mode=max",
                                                                    MaxDimension))) {AllowDestinationPathVariables = true};
                i.Build();
                
                var sitePath = Server.MapPath(@"~");
                var relativePath = i.FinalPath.Replace(sitePath, @"~/");

                var url = ResolveServerUrl(VirtualPathUtility.ToAbsolute(relativePath), false);
            //    System.IO.File.Delete(i.FinalPath);

                return Json(new { success = true, imageUrl = url }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, error = ex.Message }, "text/html", JsonRequestBehavior.AllowGet);
            }
        }

        private static string ResolveServerUrl(string serverUrl, bool forceHttps)
        {
            if (serverUrl.IndexOf("://", StringComparison.Ordinal) > -1)
                return serverUrl;

            string newUrl = serverUrl;
            Uri originalUri = System.Web.HttpContext.Current.Request.Url;
            newUrl = (forceHttps ? "https" : originalUri.Scheme) +
                     "://" + originalUri.Authority + newUrl;
            return newUrl;
        } 

        [HttpPost]
        public virtual ActionResult ReportCp(ReportCp reportCp)
        {
            _imageService.ReportCp(reportCp);
            return Json(new {success = true}, JsonRequestBehavior.AllowGet);
        }
        
    }
}

ImageMood/Controllers/MoodsController.cs
using System.Linq;
using System.Web.Mvc;
using System.Web.UI;
using ImageMood.Entities;
using ImageMood.Enums;
using ImageMood.Filters;
using ImageMood.Services;

namespace ImageMood.Controllers
{
    [JsonForAjaxCalls]
    public partial class MoodsController : Controller
    {
        private readonly IMoodsService _moodsService;
        public const int MoodsPageSize = 100;
        public const int ImagesPageSize = 100;
        //
        // GET: /Mood/
        public MoodsController(IMoodsService moodsService)
        {
            _moodsService = moodsService;
        }
        [WarnAboutIe6]
        public virtual ActionResult Index()
        {
            return View();
        }

        public virtual ActionResult GetMoods(string moodName, MoodOrder moodOrder = MoodOrder.Rating, int page = 1)
        {            
            var model = _moodsService.GetMoods(moodName, moodOrder, page, MoodsPageSize);

            return Json(model, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public virtual ActionResult AddMood(Mood mood, int imageId)
        {
            var imageMoodViewModel = _moodsService.AddMood(mood, imageId);
            return View(imageMoodViewModel);
        }

        [HttpPost]
        public virtual ActionResult Vote(int id, bool plus = true)
        {
            var model = _moodsService.VoteMood(id, plus);
            return Json(new { model.Rating }, JsonRequestBehavior.AllowGet);
        }
        public virtual ActionResult FindImages(int id, ImageOrder imageOrder = ImageOrder.Shuffle, int page = 1)
        {
            var model = _moodsService.FindImagesForMood(id, imageOrder, page, ImagesPageSize);
            return View(model);
        }

        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public virtual ActionResult CheckMoodName(string name, int? imageId)
        {
            var result = !_moodsService.IsMoodExists(name, imageId);
            return View(result);
        }

        public virtual ActionResult QuickSearch(string term)
        {
            var model = _moodsService.GetMoods(term, MoodOrder.Popular, 1, 100)
                .Select(s => new { s.Name, s.Id, label = s.Name, value = s.Name });

            return View(model);
        }
    }
}

ImageMood/Views/Moods/Index.cshtml
@using ImageMood.Entities
@using MightyHelpers.MvcHelpers
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*Feel Mood search*@
<section class="i-feel">
    <form data-bind="submit: $root.exploreMood" method="POST" action="/">
    <div class ="feel-label"><i class="icon-star"></i>I feel</div>
    <input id="moodSearch" type="text" data-bind="value: $root.foundMood" />
    </form>
</section>
@*Moods view - navigation and list*@
<section class="moods-view" data-bind="visible: view() == 'moods'">
    <nav class="list-nav">
        <ul data-bind="foreach: folders">
            <li data-bind="text: $data, 
    css: { selected: $data == $root.chosenFolder(), shuffle: $data == 'random' },
               click: $root.goToFolder"></li>
        </ul>
    </nav>
    <div class="moods">
        <div class="moods-list">
            <ul data-bind="template : {foreach: chosenMoods, afterAdd: $root.fadeIn}">
                <li data-bind="click: $root.goToMood, css: {selected: $data.Id == $root.chosenMood()}, text: Name">
                </li>
            </ul>
        </div>
    </div>
</section>
@*Images view - navigation, list and viewer*@
<section style="display: none" class="images-view" data-bind="visible: view() == 'images'">
    <nav class="list-nav">
        <ul data-bind="foreach: orders">
            <li data-bind="text: $data, 
    css: { selected: $data == $root.chosenOrder(), shuffle: $data == 'shuffle' },
               click: $root.imagesOfMood">
        </ul>
    </nav>
    <div class="images">
        <div class="info-text">
            You are exploring images of <span class="chosen" data-bind="text: $root.chosenMoodName"></span>
            mood             
            &nbsp;&nbsp;&nbsp;&bull;&nbsp;&nbsp;&nbsp;
            
            <div style="display: inline-block"><a href="/"><i class="icon-reply"></i> Back to moods list</a></div>
        </div>
        <ul class="images-list clear-fix" data-bind="template: {foreach: imagesList, afterRender: $root.fitImages}">
            <li class="hidden">
                <div class="img-container" data-bind="click: $root.goToImage">
                    <img data-bind="attr: {src: Thumb}" />
                </div>
            </li>
        </ul>
        <div style="display: none" data-bind="if: $root.anyImagesLeft, click: $root.moreImages">
            More images
        </div>
    </div>
    <section class="theater" data-bind="visible: currentImage() != null, click: $root.closeTheater">
        <i class="icon-remove" data-bind="click: $root.closeTheater"></i>
@*        <nav>
                    <!-- ko if: $root.prevImageAvailable -->
                    <i class="icon-angle-left   " data-bind="click: $root.prevImage" title="Previous image"></i>
                    <!-- /ko -->
                    <!-- ko if: $root.nextImageAvailable -->
                    <i class="icon-angle-right" data-bind="click: $root.nextImage" title="Next image"></i>
                    <!-- /ko -->
                </nav>*@
        <div class="center" data-bind="template: {if: currentImage() != null, afterRender: $root.afterImageLoad}">
            <div class="image-viewer" data-bind="with: currentImage">
                <nav>
                    <!-- ko if: $root.prevImageAvailable -->
                    <i class="icon-angle-left   " data-bind="click: $root.prevImage" title="Previous image"></i>
                    <!-- /ko -->
                    <!-- ko if: $root.nextImageAvailable -->
                    <i class="icon-angle-right" data-bind="click: $root.nextImage" title="Next image"></i>
                    <!-- /ko -->
                </nav>
                <h4 data-bind="text: Image.Name">
                </h4>
                <img data-bind="attr: {src: Image.FullUrl, alt: Image.Name}" alt="" />
                <div class="image-moods">
                    <ul data-bind="foreach: Moods">
                        <li>
                            <!-- ko with: Mood -->
                            <a href="#" class="image-mood" data-bind="text: Name, click: $root.goToMood, attr: {title: 'explore ' + Name() + ' mood'}">
                            </a>
                            <!-- /ko -->
                            <a href="#" class="votes" data-bind="css: {voted: Voted}, click: $root.vote, attr: {title: Voted() ? 'voted (cancel vote)' : 'vote this mood' }">
                                
                                    <!-- ko if: !Voted() -->
                                    <i class="icon-heart-empty"></i>
                                    <!-- /ko -->
                                <i class="icon-heart"></i>
                                <span data-bind="text: Rating"></span></a>
                        </li>
                    </ul>
                    <section class="i-feel">
                        <form id="moodAdd" data-bind="submit: $root.addMood" method="POST">
                            <div class ="feel-label"><i class="icon-star"></i>It feels</div>
                            @Html.Partial("EditorTemplates/Mood", new Mood())
                            <button type="submit" value="add" data-bind="enable: $root.moodToAdd().length > 0"
                                    title="Add mood">
                                <i class="icon-tag"></i>
                            </button>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </section>
</section>
@*Upload new image*@
<section style="display: none" class="add-image" data-bind="visible: modal() == 'addimage'">
    <section class="theater" data-bind="click: $root.closeTheater">
        <i class="icon-remove" data-bind="click: $root.closeTheater"></i>
        <div class="center">
            <div class="image-viewer" data-bind="template: {if: $root.modal() == 'addimage', afterRender: $root.fadeModal}">
                <div class="image-upload">
                    <h4>
                        Add new image</h4>
                    <div class="image-source">
                        <div class="uploaded-image hidden">
                            <span class="remove-image" title="Remove image"><i class="icon-remove icon-2x"></i>
                            </span>
                            <img />
                        </div>
                        <div class="sources">
                            <div class="dropbox">
                                <span class="message">Drag'n'drop your image here</span>
                            </div>
                            <form enctype="multipart/form-data" action="@Url.Action("Upload", "Images")" method="POST">
                                <div class="from-hard">
                                    <i class="icon-desktop icon-2x"></i>&nbsp;&nbsp;&nbsp;Upload image from computer
                                </div>
                                <input type="file" name="image" accept="image/jpeg,image/png" />
                                <div class="from-url">
                                    <i class="icon-link icon-2x"></i>
                                    <input type="url" name="imageUrl" placeholder="Upload image from url" />
                                </div>
                            </form>
                        </div>
                        <div class="progressHolder hidden">
                            <div class="progress">
                            </div>
                        </div>
                    </div>
                    <form method="POST" data-bind="submit: $root.addImage">
                        @Html.Partial("EditorTemplates/Image")
                        <input type="submit" value="Add image" />
                    </form>
                </div>
            </div>
        </div>
    </section>
</section>
<div class="ajax-center" data-bind="visible: wait()">
</div>
@using (Html.BeginScripts())
{
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/dropbox")

    <script type="text/javascript">

        var cache = {};
        var timer;
        


        $().ready(function() {
            
            $(document).keydown(function(e) {
                switch (e.keyCode) {
                case 37:
                    {
                        $('.icon-angle-left').click();
                        return false;
                    }
                case 39:
                    {
                        $('.icon-angle-right').click();
                        return false;
                    }
                case 27:
                    {
                        $('.theater').click();
                    }
                default:        
                    return true;
                }
                
            });

            $(window).resize(function() {
                clearTimeout(timer);

                timer = setTimeout(function() {
                    imageFitness.fitImages($('.images-list', false, false));
                }, 100);
            });
            var noResultsLabel = 'No moods found. Try another one';
            $('#moodSearch').autocomplete({
                minLength: 1,
                source: function(request, response) {
                    var term = request.term;
                    if (term in cache) {
                        response(cache[term]);
                        return;
                    }
                    $.get("/moods/quicksearch", request, function(data) {
                        
                        if (data.length == 0) {
                            data = [noResultsLabel];
                        }
                        cache[term] = data;
                        response(data);
                    });
                },
                select: function(event, ui) {
                    
                    if (ui.item.value != noResultsLabel) {
                        viewModel.goToMood({ Id: ui.item.Id, Name: ui.item.Name });
                    }
                    return false;
                },
            });
            uploader.setup();
        });
    </script>
}